FROM openjdk:11-jre-slim
COPY ./build/libs/*.jar app.jar
ARG DB_URL
ARG DB_USER
ARG DB_PWD
ARG AWS_S3_REGION
ARG AWS_S3_FOODIE_FOLDER
ARG AWS_S3_BUCKET
ARG AWS_S3_URL
ARG AWS_S3_ACCESS
ARG AWS_S3_SECRET

ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PWD}
ENV AWS_S3_REGION=${AWS_S3_REGION}
ENV AWS_S3_FOODIE_FOLDER=${AWS_S3_FOODIE_FOLDER}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_S3_URL=${AWS_S3_URL}
ENV AWS_S3_ACCESS=${AWS_S3_ACCESS}
ENV AWS_S3_SECRET=${AWS_S3_SECRET}

ENTRYPOINT ["java","-jar","-Dspring.datasource.url=${DB_URL}","-Dspring.datasource.username=${DB_USER}", "-Dspring.datasource.password=${DB_PWD}", "/app.jar"]
