spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://foodie-develop.csbvgeckdsn4.ap-northeast-2.rds.amazonaws.com:5432/foodie
    username: foodie
    password: vnel1234

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
